
@startuml state machine diagram
skinparam {
    defaultFontName Ricty Diminished
    monochrome true
}

state Running
state NotRunning as "Not Running" {
    state Ready
    state Blocked
    state Suspended

    [*] --> Ready
    Suspended --> Ready : Task_Resume()\n called
    Ready -> Suspended : Task_Suspend()\n called
    Blocked -up-> Ready : Event
    Blocked -up-> Suspended : Task_Suspend()\n called
}

[*] --> NotRunning : Created
Ready --> Running : Dispatched
Running -> Ready : Preempted
Running -> Blocked : Blocking API called
NotRunning --> [*] : Destroyed
Running --> [*] : Destroyed
@enduml
