
@startuml state machine diagram
skinparam {
    defaultFontName Ricty Diminished
    monochrome true
}

state Task {
    state Ready
    state Running
    state Blocked
    state Suspended

    [*] -> Ready
    Suspended --> Ready : Task_Resume()\n called
    Ready -> Suspended : Task_Suspend()\n called
    Blocked -up-> Ready : Event
    Blocked -up-> Suspended : Task_Suspend()\n called
    Ready --> Running : Dispatched
    Running -> Ready : Preempted
    Running -> Blocked : Blocking API called
    Running -> Suspended : Task_Suspend()\n called
}

[*] --> Task : Created
Task --> [*] : Destroyed
@enduml
